# CI Test - Build the action container
# build test container which has default test files and validate
name: CRDA scan
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: CRDA Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Divyansh42/spring-petclinic

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # - name: Install npm
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.7'
      # - name: Setup Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: '^1.13.1'

      # - run: |
      #     npm install

      - run: |
          mvn -Dmaven.repo.local=maven-dir clean install

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "latest"

      # - name: setup
      #   run: |
      #     mkdir -p site-dir
      #     pip3 install --target=site-dir -r teps/tools/requirements.txt
      #     cat teps/tools/requirements.txt
      - run: |
          pwd
          ls -a
          cd maven-dir
    
      - name: Run CRDA scan
        run: |
          crda config set consent_telemetry true
          crda auth -t ${{ secrets.SNYK_TOKEN }}
          crda analyse -j --verbose go.mod > crda.json

      # - name: redhat-codeready-dependency-analysis
      #   uses: fabric8-analytics/gh-actions/python-3.6@main
      #   with:
      #     manifest-file-path: package.json
      #     output-file-path: redhat-codeready-dependency-analysis-report.json
      #     pkg-installation-directory-path: .
      #   env:
      #     CRDA_KEY: ${{ secrets.CRDA_KEY }}

      - name: cat report
        run: cat crda.json
